default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: inquiry_development

test:
  <<: *default
  database: inquiry_test

production:
  <<: *default
  database: inquiry_production
  username: inquiry
  password: <%= ENV['INQUIRY_DATABASE_PASSWORD'] %>
